### PR TITLE
Added strings that are used in the stats feature implementation

### PR DESCRIPTION
**Pull request by ktruong7**

### CODE REVIEW

**Comment by mck182** [comment]
What's the source of these translations?

**Comment by anurlybayev** [comment]
Probably google. That's our new workflow

**Comment by mck182** [comment]
But then there were /so/ many new strings,
why do we bother with translations for 3 of
them? I mean, why translate a button of the
banner when the title and other text is not?
Not even the second button.

**Comment by anurlybayev** [comment]
That's a different question. Eventually all the strings should be here.

**Comment by ktruong7** [comment]
Ya, I've only added a few so far. We will need to translate the remaining strings.

**Pull request closed without merging**
